Aktive Jobs werfen bei Ausf체hrung Exception	"Wir haben einen neuen Job erstellt und auf aktiv gesetzt.

Die Seite konnte von dem WPT-Server auch nicht angesteuert werden, siehe 
http://prod.server04.otto.wpt.iteratec.de/result/160429_TG_87/1/details/ 

Als dieser ausgef체hrt wurde kam folgende Exception:

g.a.s.d.i.o.m.s.JobProcessingService Polling jobrun 160429_TG_87 of job Der Testjob: An unexpected exception occured. Error gets persisted as unfinished JobResult now
org.springframework.transaction.HeuristicCompletionException: Heuristic completion: outcome state is mixed; nested exception is org.springframework.orm.hibernate4.HibernateOptimisticLockingFailureException: Object of class [de.iteratec.osm.measurement.schedule.Job] with identifier [775]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [de.iteratec.osm.measurement.schedule.Job#775]
	at org.grails.transaction.ChainedTransactionManager.commit(ChainedTransactionManager.java:183)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:150)
	at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
	at de.iteratec.osm.measurement.environment.wptserverproxy.LocationAndResultPersisterService.persistJobResult(LocationAndResultPersisterService.groovy)
	at de.iteratec.osm.measurement.environment.wptserverproxy.LocationAndResultPersisterService$persistJobResult$0.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at de.iteratec.osm.measurement.environment.wptserverproxy.LocationAndResultPersisterService.listenToResult(LocationAndResultPersisterService.groovy:119)
	at de.iteratec.osm.measurement.environment.wptserverproxy.iListener$listenToResult.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at de.iteratec.osm.measurement.environment.wptserverproxy.ProxyService$_fetchResult_closure2.doCall(ProxyService.groovy:159)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
	at groovy.lang.Closure.call(Closure.java:426)
	at de.iteratec.osm.measurement.environment.wptserverproxy.ProxyService$_fetchResult_closure2.call(ProxyService.groovy)
	at groovy.lang.Closure.call(Closure.java:442)
	at de.iteratec.osm.measurement.environment.wptserverproxy.ProxyService$_fetchResult_closure2.call(ProxyService.groovy)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2030)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2015)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2056)
	at org.codehaus.groovy.runtime.dgm$162.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at de.iteratec.osm.measurement.environment.wptserverproxy.ProxyService.fetchResult(ProxyService.groovy:158)
	at de.iteratec.osm.measurement.environment.wptserverproxy.ProxyService$fetchResult$1.call(Unknown Source)
	at de.iteratec.osm.measurement.schedule.JobProcessingService.pollJobRun(JobProcessingService.groovy:372)
	at de.iteratec.osm.measurement.schedule.JobProcessingService.pollJobRun(JobProcessingService.groovy)
	at de.iteratec.osm.measurement.schedule.JobProcessingService$pollJobRun$11.call(Unknown Source)
	at de.iteratec.osm.measurement.schedule.quartzjobs.CronDispatcherQuartzJob.execute(CronDispatcherQuartzJob.groovy:57)
	at sun.reflect.GeneratedMethodAccessor879.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
	at grails.plugins.quartz.GrailsJobFactory$GrailsJob.execute(GrailsJobFactory.java:102)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.springframework.orm.hibernate4.HibernateOptimisticLockingFailureException: Object of class [de.iteratec.osm.measurement.schedule.Job] with identifier [775]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [de.iteratec.osm.measurement.schedule.Job#775]
	at org.springframework.orm.hibernate4.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:202)
	at org.springframework.orm.hibernate4.HibernateTransactionManager.convertHibernateAccessException(HibernateTransactionManager.java:730)
	at org.springframework.orm.hibernate4.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:592)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:761)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:730)
	at org.grails.transaction.MultiTransactionStatus.commit(MultiTransactionStatus.java:73)
	at org.grails.transaction.ChainedTransactionManager.commit(ChainedTransactionManager.java:156)
	... 48 common frames omitted
Caused by: org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [de.iteratec.osm.measurement.schedule.Job#775]
	at org.hibernate.persister.entity.AbstractEntityPersister.check(AbstractEntityPersister.java:2541)
	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3285)
	at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:3183)
	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3525)
	at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:159)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:465)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:351)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:350)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56)
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1258)
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:425)
	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)
	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:177)
	at org.springframework.orm.hibernate4.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:584)
	... 52 common frames omitted"		Bug	OpenSpeedMonitor	29/Apr/16 9:09 AM	02/May/16 3:13 PM														02/May/16 3:12 PM;msk;Kann nicht reproduziert werden. Wenn ich auf Re-Run im WPT-Server klicke, l채uft der auch durch. Vielleicht gab es im WPT-Server intern einen Fehler? 	02/May/16 3:13 PM;msk;Kann nicht reproduziert werden. Wenn ich auf Re-Run im WPT-Server klicke, l채uft der auch durch. Vielleicht gab es im WPT-Server intern einen Fehler? 																																																					
