Aktualisierung mongodb-Plugin	"Funktionieren alle Plugins/unsere Grails-Version noch mit dem neuen mongodb-Plugin zusammen.

"		Task	OpenSpeedMonitor	07/Mar/16 4:12 PM	18/May/16 5:09 PM														"25/Mar/16 2:48 PM;bwo;Es scheint Probleme mit unseren Grails Version und unseren Plugins zu geben, wodurch wir das Plugin aktuell nicht updaten können. 

Unabhängig davon haben wir beschlossen, die Daten aus der MongoDB möglichst unbehandelt direkt an den Browser zu leiten, das Plugin würde die Objekte zuvor in Groovy-Objekte konvertieren und wir müssen sie anschließend in ein JSON zurück konvertieren.



Eine mögliche Alternative wäre http://mongodb.github.io/mongo-java-driver-reactivestreams/"	"06/Apr/16 8:24 AM;bwo;Nils:

""Was mongodb angeht: Ich denke wir sollten uns nochmal genauer ansehen, warum das aktuellere Plugin nicht lief und sehen, ob wir das nicht doch zum Laufen bekommen. Auch das Low Level API, dass ich benutzen wollte, um json direkt rauszuschreiben beruht nämlich darauf.



[5:56] 

@bwo Könntest Du das Ticket für das Update bitte nochmal aufmachen und genauer beschreiben, was nicht funktioniert hat?"""	"06/Apr/16 9:00 AM;bwo;Bei dem Versuch einfach die Plugin Version zu erhöhen, endet der Start mit folgendem Fehler:



context.GrailsContextLoaderListener Error initializing the application: Could not find matching constructor for: org.grails.datastore.gorm.bootstrap.AbstractDatastoreInitializer(groovy.util.ConfigObject, java.util.ArrayList)

groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.grails.datastore.gorm.bootstrap.AbstractDatastoreInitializer(groovy.util.ConfigObject, java.util.ArrayList)

	at MongodbGrailsPlugin$_closure1.doCall(MongodbGrailsPlugin.groovy:33)

	at grails.spring.BeanBuilder.invokeBeanDefiningClosure(BeanBuilder.java:754)

	at grails.spring.BeanBuilder.beans(BeanBuilder.java:584)

	at grails.spring.BeanBuilder.invokeMethod(BeanBuilder.java:527)

	at java.util.concurrent.FutureTask.run(FutureTask.java:262)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)

	at java.lang.Thread.run(Thread.java:745)



Process finished with exit code 1



Ich habe eine neue Anwendung erstellt und die neue Plugin Version genutzt und konnte damit erfolgreich starten. Der Fehler wird folglich von einem unserer anderen Plugins verursacht. Ich werde nun nach und nach alle Plugins durchgehen."	"06/Apr/16 12:07 PM;bwo;Mit grails 2.5.0 und einer frischen Anwendung muss in der DataSource.groovy die Hibernate configuration auskommentiert werden. Fügt man nun jedoch eine Domain hinzu, so startet die Anwendung wieder nicht.



Ich habe das ganze dann mit grails 3.1.4 versucht. Damit funktioniert es problemlos. Ich bin dabei auf folgendes Ticket gestoßen: https://github.com/grails/grails-data-mapping/issues/592

Scheinbar müssen wir in Zukunft auch hibernate4 nutzen. Das ist auch der grails 3.1 default.



Somit scheint eine Möglichkeit das Upgrade auf 3.1.4 zu sein, damit hätten wir auch die aktuellste Version. Wir müssten jedoch für alle Plugins überprüfen, ob es eine aktuelle Version gibt."	18/May/16 5:09 PM;nku;Nicht mehr nötig, da wir das Detaildaten-Dashboard auslagern in einen Microservice.																																																		
